<a href="https://colab.research.google.com/github/evc-morris/pandas/blob/main/Copy_of_EM_cloud_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np


# Numpy


### n-dimensional array: A collection of elements




In [ ]:
a_py = [10, 20, 30, 40, 23, 123, 1233]

In [ ]:
type(a_py)

list

In [ ]:
b_np = np.array([10, 20, 30, 40, 23, 123, 1233])

In [ ]:
a_py

[10, 20, 30, 40, 23, 123, 1233]

In [ ]:
b_np

array([  10,   20,   30,   40,   23,  123, 1233])

In [ ]:
#multiply all numbers by 10


In [ ]:
#without numpy
arr = []
for i in a_py:
  arr.append(i * 10)



In [ ]:
arr

[100, 200, 300, 400, 230, 1230, 12330]

In [ ]:
# with numpy
b_np * 10

array([  100,   200,   300,   400,   230,  1230, 12330])

In [ ]:
# numpy arrays contain only one datatype 
# example of implicit upcasting

In [ ]:
c_np = np.array([1, 2.0, 3])

In [ ]:
c_np

array([1., 2., 3.])

In [ ]:
c_np.dtype
# all will be upcast to floats

dtype('float64')